parameters:
  BAG2CSV_PATH: "./bag2csv_data/multiego_bag2"
  FILE_NAME: "/frame_"
  # ground removal
  MAPDATA_TYPE: 0
  THRESHOLD_dM: 0.5
  MAX_RANGE: 150.0
  MIN_RANGE: 3.0
  RANGE_RESOLUTION: 0.3
  N_HORIZONTAL: 1024
  N_FILTER_CHANNEL: 40
  THRESHOLD_Z: 2.0
  # clustering object
  THRESHOLD_HEIGHT_GAP: 0.3
  THRESHOLD_DISTANCE2BORDER: 1.7
  DBSCAN_PTS: 4
  DBSCAN_EPS: 1.5
  # contour extraction
  CONTOUR_RES: 0.5
  CONTOUR_Z_THRH : 0.5
  SYMMETRIC_MAX_AREA: 0.56
  CONTOUR_MIN_AREA: 0.01
  CONTOUR_MAX_AREA: 1.5
  CONTOUR_ORTHO_MIN: 75
  CONTOUR_OUTLIER_MAX: 0.9


  # pcd2bin
  FOLDER_NAME: "/../../../../bag2bin_data"
  BAG_NAME: "/multiego_bag2"

  # bin publisher
  FRAME_ID: 486
  RATE: 10

