parameters:
  # ground removal
  MAPDATA_TYPE: 1
  THRESHOLD_dM: 0.5
  MAX_RANGE: 150.0
  MIN_RANGE: 3.0
  RANGE_RESOLUTION: 0.3
  N_HORIZONTAL: 1024
  N_FILTER_CHANNEL: 40
  THRESHOLD_Z: 2.0
  THRESHOLD_HEIGHT_GAP: 0.3
  # clustering object
  THRESHOLD_DISTANCE2BORDER: 1.7
  DBSCAN_PTS: 4
  DBSCAN_EPS: 1.5
  # contour extraction
  CONTOUR_RES: 0.5
  CONTOUR_Z_THRH : 0.5
  SYMMETRIC_MAX_AREA: 0.2
  CONTOUR_MIN_AREA: 0.01
  CONTOUR_MAX_AREA: 1.5
  CONTOUR_ORTHO_MIN: 60
